### ISSUE TITLE
Not compatible with K2 mode in latest IntelliJ IDEA

### ISSUE THREAD

**Issue by IlyaNerd** [s4nchez/okey-doke-idea#8]
IntelliJ reports that plugin Okey-doke support is not compatible with K2 mode.

Steps:
- Download latest IntelliJ (2024.2) 
- Enable K2 mode in the settings
- Restart IDE

Can this plugin be updated to be compatible?

Note: IntelliJ team aims to have the K2 enabled by default in 2024.3 version.

**Comment by gruffT** [comment]
+1 on this issue.

I have a branch with the required changes, build dependencies and a declaration in `plugin.xml`.

Happy to contribute or send a patch if you prefer.

**Comment by IlyaNerd** [comment]
Its actually working in 2024.3 as is.
